// ArcObjectsScript.idl : IDL source for ArcObjectsScript
//

// This file will be processed by the MIDL tool to
// produce the type library (ArcObjectsScript.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(4BC4FDCF-878D-42DB-A28E-ED2927DC2D8E),
    dual,
    nonextensible,
    helpstring("IArcObjectsFeatureClass Interface"),
    pointer_default(unique)
]
interface IArcObjectsFeatureClass : IDispatch{
};
[
    uuid(DAE30B55-BB5F-436E-8A60-5E6CD71E9050),
    version(1.0),
    helpstring("ArcObjectsScript 1.0 Type Library")
]
library ArcObjectsScriptLib
{
    importlib("stdole2.tlb");

    //
    //
    //

    [
        object,
        uuid(2B86F8EE-B8D1-46DE-BF5F-D27FF81070C9),
        dual,
        nonextensible,
        helpstring("IArcObjects Interface"),
        pointer_default(unique)
    ]
    interface IArcObjects : IDispatch{
        
        //----------------------------------------------------------------------

        [id(61)] HRESULT IsClass([in] VARIANT* obj, [out, retval] VARIANT_BOOL* result);
        [id(62)] HRESULT Class_Fields([in] VARIANT* obj, [out, retval] VARIANT* result);

        //----------------------------------------------------------------------

        [id(71)] HRESULT IsField([in] VARIANT* obj, [out, retval] VARIANT_BOOL* result);
        [id(72)] HRESULT Field_Name([in] VARIANT* obj, [out, retval] BSTR* fieldName);

        //----------------------------------------------------------------------

        [id(81)] HRESULT IsDomain([in] VARIANT* obj, [out, retval] VARIANT_BOOL* result);

        //----------------------------------------------------------------------

        [id(41)] HRESULT IsSubtypes([in] VARIANT* obj, [out, retval] VARIANT_BOOL* result);
        [id(42)] HRESULT Subtypes_HasSubtype([in] VARIANT* obj, [out, retval] VARIANT_BOOL* result);
        [id(43)] HRESULT Subtypes_DefaultSubtypeCode([in] VARIANT* obj, [out, retval] LONG* result);
        [id(44)] HRESULT Subtypes_SetDefaultSubtypeCode([in] VARIANT* obj, [in] LONG subtypeCode);
        [id(45)] HRESULT Subtypes_DefaultValue([in] VARIANT* obj, [in] LONG subtypeCode, BSTR fieldName, [out, retval] VARIANT* result);
        [id(46)] HRESULT Subtypes_SetDefaultValue([in] VARIANT* obj, [in] LONG subtypeCode, BSTR fieldName, [in] VARIANT value);
        [id(47)] HRESULT Subtypes_Domain([in] VARIANT* obj, [in] LONG subtypeCode, BSTR fieldName, [out, retval] VARIANT* result);
        [id(48)] HRESULT Subtypes_SetDomain([in] VARIANT* obj, [in] LONG subtypeCode, BSTR fieldName, [in] VARIANT* domain);
        [id(49)] HRESULT Subtypes_SubtypeFieldName([in] VARIANT* obj, [out, retval] BSTR* fieldName);
        [id(50)] HRESULT Subtypes_SetSubtypeFieldName([in] VARIANT* obj, [in] BSTR fieldName);
        [id(51)] HRESULT Subtypes_SubtypeFieldIndex([in] VARIANT* obj, [out,retval] LONG* index);
        [id(52)] HRESULT Subtypes_SubtypeName([in] VARIANT* obj, [in] LONG subtypeCode, [out,retval] BSTR* subtypeName);
        [id(53)] HRESULT Subtypes_Subtypes([in] VARIANT* obj, [out,retval] VARIANT* enumSubtypes);
        [id(54)] HRESULT Subtypes_AddSubtype([in] VARIANT* obj, [in] LONG subtypeCode, [in] BSTR subtypeName);
        [id(55)] HRESULT Subtypes_DeleteSubtype([in] VARIANT* obj, [in] LONG subtypeCode);

        //----------------------------------------------------------------------

        //[id(61)] HRESULT IsEnumSubtype([in] VARIANT* obj, [out, retval] VARIANT_BOOL* result);
        //[id(62)] HRESULT EnumSubtype_Next([in] VARIANT* obj, [out] LONG* subtypeCode, [out, retval] BSTR* subtypeName);
        //[id(63)] HRESULT EnumSubtype_Reset([in] VARIANT* obj);

        //
        //
        //

        [id(90)] HRESULT FeatureClass([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(100)] HRESULT FeatureLayer([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(101)] HRESULT FeatureLayerDefinition([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(102)] HRESULT FeatureLayerExtendedDefinition([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(103)] HRESULT Layer([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(113)] HRESULT Map([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(123)] HRESULT MapDocument([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);


    };

    [
        uuid(28769970-F310-4461-8F7A-809170A485C9),
        helpstring("ArcObjects Class")
    ]
    coclass ArcObjects
    {
        [default] interface IArcObjects;
    };

    //
    //
    //

    [
        object,
        uuid(46D538AA-09F6-41b2-8B54-DCA59AD66335),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayer : IDispatch{
        [id(18), propget] HRESULT FeatureClass([out, retval] VARIANT* featureClass);
    }

    //
    //
    //

    [
        uuid(F486D1BA-6EB6-481F-B446-93908A1B55A0),
        helpstring("ArcObjectsFeatureLayer Class")
    ]
    coclass ArcObjectsFeatureLayer
    {
        [default] interface IArcObjectsFeatureLayer;
    };

    //
    //
    //

    [
        object,
        uuid(EDEBC24E-0607-4E49-89DD-44E65B5A4194),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayerDefinition Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayerDefinition : IDispatch{
        [propget] HRESULT DefinitionExpression([out, retval] BSTR* expression);
    };

    //
    //
    //

    [
        uuid(9841539F-1640-4957-A244-425BC461BA44),
        helpstring("ArcObjectsFeatureLayerDefinition Class")
    ]
    coclass ArcObjectsFeatureLayerDefinition
    {
        [default] interface IArcObjectsFeatureLayerDefinition;
    };

    //
    //
    //

    [
        object,
        uuid(1E2BF6C5-97DB-453A-97DC-2A67F5600652),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayerExtendedDefinition Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayerExtendedDefinition : IDispatch{
    };

    //
    //
    //

    [
        uuid(A4F5A94C-41B0-4C8B-B421-4497EE3C53D6),
        helpstring("ArcObjectsFeatureLayerExtendedDefinition Class")
    ]
    coclass ArcObjectsFeatureLayerExtendedDefinition
    {
        [default] interface IArcObjectsFeatureLayerExtendedDefinition;
    };

    //
    //
    //

    [
        object,
        uuid(6B8647B7-618D-4CCF-85D4-1DA37A5A850E),
        dual,
        nonextensible,
        helpstring("IArcObjectsMapDocument Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsMapDocument : IDispatch{
        [propget] HRESULT MapCount([out, retval] LONG* mapCount);
        HRESULT Map(LONG index, [out, retval] VARIANT* map);
    };

    //
    //
    //

    [
        uuid(F4441B0B-52FA-4064-AFFF-EFA435D72773),
        helpstring("ArcObjectsMapDocument Class")
    ]
    coclass ArcObjectsMapDocument
    {
        [default] interface IArcObjectsMapDocument;
    };

    //
    //
    //

    [
        object,
        uuid(6F983B78-D22F-4366-8BDC-523EFFAABD1D),
        dual,
        nonextensible,
        helpstring("IArcObjectsMap Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsMap : IDispatch{
        [propget] HRESULT LayerCount([out, retval] LONG* layerCount);
        HRESULT Layer(LONG index, [out, retval] VARIANT* layer);
    };

    //
    //
    //

    [
        uuid(CFE34595-9E4F-4805-88F5-BA47E4E7BABA),
        helpstring("ArcObjectsMap Class")
    ]
    coclass ArcObjectsMap
    {
        [default] interface IArcObjectsMap;
    };

    //
    //
    //

    [
        object,
        uuid(273A1ED0-9C14-4E3F-AAEB-3A9611517225),
        dual,
        nonextensible,
        helpstring("IArcObjectsLayer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsLayer : IDispatch{
        [propget] HRESULT Name([out, retval] BSTR* name);
        [propput] HRESULT Name([in] BSTR name);
    };

    //
    //
    //

    [
        uuid(E56DAD49-03A9-4AB3-8E9D-D861F98B95A3),
        helpstring("ArcObjectsLayer Class")
    ]
    coclass ArcObjectsLayer
    {
        [default] interface IArcObjectsLayer;
    };

    //
    //
    //


    [
        uuid(F031CF0C-88CA-482C-9FF8-188300272205),
        helpstring("ArcObjectsFeatureClass Class")
    ]
    coclass ArcObjectsFeatureClass
    {
        [default] interface IArcObjectsFeatureClass;
    };
};
