// ArcObjectsScript.idl : IDL source for ArcObjectsScript
//

// This file will be processed by the MIDL tool to
// produce the type library (ArcObjectsScript.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

enum
{
    PROPID_BASE = 1024,
    PROPID_Description,
    PROPID_DomainID,
    PROPID_FieldType,
    PROPID_MergePolicy,
    PROPID_Name,
    PROPID_Owner,
    PROPID_SplitPolicy,
    PROPID_Type,

    METHID_BASE = 2048,
    METHID_MemberOf,
};

[
    uuid(DAE30B55-BB5F-436E-8A60-5E6CD71E9050),
    version(1.0),
    helpstring("ArcObjectsScript 1.0 Type Library")
]
library ArcObjectsScriptLib
{
    importlib("stdole2.tlb");

    //
    //
    //

    [
        object,
        uuid(2B86F8EE-B8D1-46DE-BF5F-D27FF81070C9),
        dual,
        nonextensible,
        helpstring("IArcObjects Interface"),
        pointer_default(unique)
    ]
    interface IArcObjects : IDispatch{
        [id(80)] HRESULT Domain([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(90)] HRESULT FeatureClass([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(100)] HRESULT FeatureLayer([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(101)] HRESULT FeatureLayerDefinition([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(102)] HRESULT FeatureLayerExtendedDefinition([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(12)] HRESULT Field([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(103)] HRESULT Layer([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(113)] HRESULT Map([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(123)] HRESULT MapDocument([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);
        [id(133)] HRESULT Subtypes([in, optional] VARIANT* inner, [out,retval] VARIANT* outer);


    };

    [
        uuid(28769970-F310-4461-8F7A-809170A485C9),
        helpstring("ArcObjects Class")
    ]
    coclass ArcObjects
    {
        [default] interface IArcObjects;
    };

    //
    //
    //

    [
        object,
        uuid(46D538AA-09F6-41b2-8B54-DCA59AD66335),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayer : IDispatch{
        [id(18), propget] HRESULT FeatureClass([out, retval] VARIANT* featureClass);
    }

    //
    //
    //

    [
        uuid(F486D1BA-6EB6-481F-B446-93908A1B55A0),
        helpstring("ArcObjectsFeatureLayer Class")
    ]
    coclass ArcObjectsFeatureLayer
    {
        [default] interface IArcObjectsFeatureLayer;
    };

    //
    //
    //

    [
        object,
        uuid(EDEBC24E-0607-4E49-89DD-44E65B5A4194),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayerDefinition Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayerDefinition : IDispatch{
        [propget] HRESULT DefinitionExpression([out, retval] BSTR* expression);
    };

    //
    //
    //

    [
        uuid(9841539F-1640-4957-A244-425BC461BA44),
        helpstring("ArcObjectsFeatureLayerDefinition Class")
    ]
    coclass ArcObjectsFeatureLayerDefinition
    {
        [default] interface IArcObjectsFeatureLayerDefinition;
    };

    //
    //
    //

    [
        object,
        uuid(1E2BF6C5-97DB-453A-97DC-2A67F5600652),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayerExtendedDefinition Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayerExtendedDefinition : IDispatch{
    };

    //
    //
    //

    [
        uuid(A4F5A94C-41B0-4C8B-B421-4497EE3C53D6),
        helpstring("ArcObjectsFeatureLayerExtendedDefinition Class")
    ]
    coclass ArcObjectsFeatureLayerExtendedDefinition
    {
        [default] interface IArcObjectsFeatureLayerExtendedDefinition;
    };

    //
    //
    //

    [
        object,
        uuid(6B8647B7-618D-4CCF-85D4-1DA37A5A850E),
        dual,
        nonextensible,
        helpstring("IArcObjectsMapDocument Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsMapDocument : IDispatch{
        [propget] HRESULT MapCount([out, retval] LONG* mapCount);
        HRESULT Map(LONG index, [out, retval] VARIANT* map);
    };

    //
    //
    //

    [
        uuid(F4441B0B-52FA-4064-AFFF-EFA435D72773),
        helpstring("ArcObjectsMapDocument Class")
    ]
    coclass ArcObjectsMapDocument
    {
        [default] interface IArcObjectsMapDocument;
    };

    //
    //
    //

    [
        object,
        uuid(6F983B78-D22F-4366-8BDC-523EFFAABD1D),
        dual,
        nonextensible,
        helpstring("IArcObjectsMap Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsMap : IDispatch{
        [propget] HRESULT LayerCount([out, retval] LONG* layerCount);
        HRESULT Layer(LONG index, [out, retval] VARIANT* layer);
    };

    //
    //
    //

    [
        uuid(CFE34595-9E4F-4805-88F5-BA47E4E7BABA),
        helpstring("ArcObjectsMap Class")
    ]
    coclass ArcObjectsMap
    {
        [default] interface IArcObjectsMap;
    };

    //
    //
    //

    [
        object,
        uuid(273A1ED0-9C14-4E3F-AAEB-3A9611517225),
        dual,
        nonextensible,
        helpstring("IArcObjectsLayer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsLayer : IDispatch{
        [propget] HRESULT Name([out, retval] BSTR* name);
        [propput] HRESULT Name([in] BSTR name);
    };

    //
    //
    //

    [
        uuid(E56DAD49-03A9-4AB3-8E9D-D861F98B95A3),
        helpstring("ArcObjectsLayer Class")
    ]
    coclass ArcObjectsLayer
    {
        [default] interface IArcObjectsLayer;
    };

    //
    //
    //

    [
        object,
        uuid(22B75AA7-23FC-4F76-8471-C20789509FF1),
        dual,
        nonextensible,
        helpstring("IArcObjectsSubtypes Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsSubtypes : IDispatch{
        [propget] HRESULT HasSubtype([out, retval] VARIANT_BOOL* hasSubtype);
        [propget] HRESULT DefaultSubtypeCode([out, retval] LONG* subtypeCode);
        [propput] HRESULT DefaultSubtypeCode([in] LONG subtypeCode);
        HRESULT GetDefaultValue([in] LONG subtypeCode, [in] BSTR fieldName, [out, retval] VARIANT* value);
        HRESULT SetDefaultValue([in] LONG subtypeCode, [in] BSTR fieldName, [in] VARIANT value);
        HRESULT GetDomain([in] LONG subtypeCode, [in] BSTR fieldName, [out, retval] VARIANT* domain);
        HRESULT SetDomain([in] LONG subtypeCode, [in] BSTR fieldName, [in] VARIANT* domain);
        [propget] HRESULT SubtypeFieldName([out, retval] BSTR* fieldName);
        [propput] HRESULT SubtypeFieldName([in] BSTR fieldName);
        [propget] HRESULT SubtypeFieldIndex([out, retval] LONG* index);
        HRESULT GetSubtypeName([in] LONG subtypeCode, [out, retval] BSTR* value);
        [propget] HRESULT Subtypes([out, retval] VARIANT* subtypes);
        HRESULT AddSubtype([in] LONG subtypeCode, [in] BSTR subtypeName);
        HRESULT DeleteSubtype([in] LONG subtypeCode);
    };

    //
    //
    //

    [
        uuid(9CED7FA7-2522-4730-805E-88555783F05C),
        helpstring("ArcObjectsSubtypes Class")
    ]
    coclass ArcObjectsSubtypes
    {
        [default] interface IArcObjectsSubtypes;
    };

    //
    //
    //

    [
        object,
        uuid(4BBBE44F-A3BA-40F0-ACA5-C5396C3D9FBD),
        dual,
        nonextensible,
        helpstring("IArcObjectsDomain Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsDomain : IDispatch{
        [id(PROPID_DomainID), propget] HRESULT DomainID([out, retval] LONG* domainID);
        [id(PROPID_DomainID), propput] HRESULT DomainID([in] LONG domainID);
        [id(PROPID_Description), propget] HRESULT Description([out, retval] BSTR* description);
        [id(PROPID_Description), propput] HRESULT Description([in] BSTR description);
        [id(PROPID_FieldType), propget] HRESULT FieldType([out, retval] LONG* fieldType);
        [id(PROPID_FieldType), propput] HRESULT FieldType([in] LONG fieldType);
        [id(PROPID_MergePolicy), propget] HRESULT MergePolicy([out, retval] LONG* mergePolicy);
        [id(PROPID_MergePolicy), propput] HRESULT MergePolicy([in] LONG mergePolicy);
        [id(PROPID_SplitPolicy), propget] HRESULT SplitPolicy([out, retval] LONG* splitPolicy);
        [id(PROPID_SplitPolicy), propput] HRESULT SplitPolicy([in] LONG splitPolicy);
        [id(PROPID_Name), propget] HRESULT Name([out, retval] BSTR* name);
        [id(PROPID_Name), propput] HRESULT Name([in] BSTR name);
        [id(PROPID_Owner), propget] HRESULT Owner([out, retval] BSTR* description);
        [id(PROPID_Owner), propput] HRESULT Owner([in] BSTR description);
        [id(PROPID_Type), propget] HRESULT Type([out, retval] LONG* type);
        [id(METHID_MemberOf)] HRESULT MemberOf([in] VARIANT value, [out, retval] VARIANT_BOOL* isMember);
    };

    //
    //
    //

    [
        uuid(3C7DB8B9-C332-4188-822C-9815CA65222A),
        helpstring("ArcObjectsDomain Class")
    ]
    coclass ArcObjectsDomain
    {
        [default] interface IArcObjectsDomain;
    };

    //
    //
    //

    [
        object,
        uuid(BD55CC31-347E-4E17-A00F-182A9D04BED3),
        dual,
        nonextensible,
        helpstring("IArcObjectsClass Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsClass : IDispatch{
        [propget] HRESULT Fields([out, retval] VARIANT* fields);
    };

    //
    //
    //

    [
        uuid(1CBEC865-753B-47F3-952F-D87386824729),
        helpstring("ArcObjectsClass Class")
    ]
    coclass ArcObjectsClass
    {
        [default] interface IArcObjectsClass;
    };


    //
    //
    //

    [
        object,
        uuid(4BC4FDCF-878D-42DB-A28E-ED2927DC2D8E),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureClass Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureClass : IArcObjectsClass {
    };

    //
    //
    //

    [
        uuid(F031CF0C-88CA-482C-9FF8-188300272205),
        helpstring("ArcObjectsFeatureClass Class")
    ]
    coclass ArcObjectsFeatureClass
    {
        [default] interface IArcObjectsFeatureClass;
    };

    [
        object,
        uuid(56504920-EFE1-4448-9CD4-AD2C2DA28F31),
        dual,
        nonextensible,
        helpstring("IArcObjectsField Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsField : IDispatch{
        [propget] HRESULT Name([out, retval] BSTR* name);
    };

    //
    //
    //

    [
        uuid(46711B21-F34D-4EBB-BCB1-021909A1AA7C),
        helpstring("ArcObjectsField Class")
    ]
    coclass ArcObjectsField
    {
        [default] interface IArcObjectsField;
    };

    //
    //
    //

};
