    [
        object,
        uuid(4BBBE44F-A3BA-40F0-ACA5-C5396C3D9FBD),
        dual,
        nonextensible,
        helpstring("IArcObjectsDomain Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsDomain : IDispatch{
        [id(PROPID_DomainID), propget] HRESULT DomainID([out, retval] LONG* domainID);
        [id(PROPID_DomainID), propput] HRESULT DomainID([in] LONG domainID);
        [id(PROPID_Description), propget] HRESULT Description([out, retval] BSTR* description);
        [id(PROPID_Description), propput] HRESULT Description([in] BSTR description);
        [id(PROPID_FieldType), propget] HRESULT FieldType([out, retval] LONG* fieldType);
        [id(PROPID_FieldType), propput] HRESULT FieldType([in] LONG fieldType);
        [id(PROPID_MergePolicy), propget] HRESULT MergePolicy([out, retval] LONG* mergePolicy);
        [id(PROPID_MergePolicy), propput] HRESULT MergePolicy([in] LONG mergePolicy);
        [id(PROPID_SplitPolicy), propget] HRESULT SplitPolicy([out, retval] LONG* splitPolicy);
        [id(PROPID_SplitPolicy), propput] HRESULT SplitPolicy([in] LONG splitPolicy);
        [id(PROPID_Name), propget] HRESULT Name([out, retval] BSTR* name);
        [id(PROPID_Name), propput] HRESULT Name([in] BSTR name);
        [id(PROPID_Owner), propget] HRESULT Owner([out, retval] BSTR* description);
        [id(PROPID_Owner), propput] HRESULT Owner([in] BSTR description);
        [id(PROPID_Type), propget] HRESULT Type([out, retval] LONG* type);
        [id(METHID_MemberOf)] HRESULT MemberOf([in] VARIANT value, [out, retval] VARIANT_BOOL* isMember);
    };

    [
        uuid(3C7DB8B9-C332-4188-822C-9815CA65222A),
        helpstring("ArcObjectsDomain Class")
    ]
    coclass ArcObjectsDomain
    {
        [default] interface IArcObjectsDomain;
    };