// ArcObjectsScript.idl : IDL source for ArcObjectsScript
//

// This file will be processed by the MIDL tool to
// produce the type library (ArcObjectsScript.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

//
//
//

enum
{
    //
    //
    //

    PROPID_A = 0x10100,
    PROPID_AliasName,
    PROPID_AreaField,
	PROPID_AreaOfInterest,

    PROPID_C = 0x10300,
	PROPID_Cached,
	PROPID_CLSID,

    PROPID_D = 0x10400,
    PROPID_DefaultSubtypeCode,
    PROPID_DefinitionExpression,
    PROPID_Description,
    PROPID_DomainID,

    PROPID_E = 0x10500,
    PROPID_Extension,
    PROPID_ExtensionProperties,
    PROPID_EXTCLSID,

    PROPID_F = 0x10600,
    PROPID_FeatureClass,
    PROPID_FeatureDataset,
    PROPID_FeatureType,
    PROPID_Fields,
    PROPID_FieldType,

    PROPID_H = 0x10800,
    PROPID_HasOID,
    PROPID_HasSubtype,

    PROPID_I = 0x10900,
    PROPID_Indexes,

    PROPID_J = 0x10A00,

    PROPID_K = 0x10B00,

    PROPID_L = 0x10C00,
    PROPID_LayerCount,
    PROPID_LengthField,

    PROPID_M = 0x10D00,
    PROPID_MapCount,
	PROPID_MaximumScale,
	PROPID_MergePolicy,
	PROPID_MinimumScale,

    PROPID_N = 0x10E00,
    PROPID_Name,

    PROPID_O = 0x10F00,
    PROPID_ObjectClassID,
    PROPID_OIDFieldName,
    PROPID_Owner,

    PROPID_P = 0x11000,
    PROPID_Q = 0x11100,

    PROPID_R = 0x11200,
    PROPID_RelationshipClasses,

    PROPID_S = 0x11300,
    PROPID_ShapeFieldName,
    PROPID_ShapeType,
	PROPID_ShowTips,
	PROPID_SpatialReference,
	PROPID_SplitPolicy,
    PROPID_SubFields,
    PROPID_SubtypeFieldIndex,
    PROPID_SubtypeFieldName,
    PROPID_Subtypes,
	PROPID_SupportedDrawPhases,

    PROPID_T = 0x11400,
	PROPID_Type,

    PROPID_U = 0x11500,

    PROPID_V = 0x11600,
	PROPID_Valid,
	PROPID_Visible,

    PROPID_W = 0x11700,
    PROPID_WhereClause,

	PROPID_X = 0x11800,

	PROPID_Y = 0x11900,

	PROPID_Z = 0x11A00,

	//
    //
    //

    METHID_A = 0x20100,
    METHID_AddField,
    METHID_AddIndex,
    METHID_AddSubtype,

    METHID_C = 0x20300,
    METHID_CreateFeature,
    METHID_CreateFeatureBuffer,

    METHID_D = 0x20400,
    METHID_DeleteFeature,
    METHID_DeleteField,
    METHID_DeleteIndex,
    METHID_DeleteSubtype,
    METHID_Domain,
	METHID_Draw,

    METHID_F = 0x20600,
    METHID_Feature,
    METHID_FeatureClass,
    METHID_FeatureCount,
    METHID_FeatureDataset,
    METHID_FeatureLayer,
    METHID_FeatureLayerDefinition,
    METHID_FeatureLayerExtendedDefinition,
    METHID_Field,
    METHID_FindField,
    METHID_Flush,

    METHID_G = 0x20700,
    METHID_GetDefaultValue,
    METHID_GetDomain,
    METHID_GetFeatures,
    METHID_GetOutputSpatialReference,
    METHID_GetSubtypeName,
	METHID_GetTipText,

    METHID_H = 0x20800,

    METHID_I = 0x20900,
    METHID_Insert,
    METHID_InsertFeature,

    METHID_J = 0x20A00,

    METHID_K = 0x20B00,

    METHID_L = 0x20C00,
    METHID_Layer,

    METHID_M = 0x20D00,
    METHID_Map,
    METHID_MapDocument,
    METHID_MemberOf,

    METHID_N = 0x20E00,
    METHID_NextFeature,

    METHID_O = 0x20F00,
    METHID_ObjectClass,

    METHID_P = 0x21000,

    METHID_Q = 0x21100,
    METHID_QueryFilter,

    METHID_R = 0x21200,
    METHID_Row,

    METHID_S = 0x21300,
    METHID_Search,
    METHID_Select,
    METHID_SelectionSet,
    METHID_SetDefaultValue,
    METHID_SetDomain,
    METHID_SetOutputSpatialReference,
    METHID_SpatialReference,
    METHID_Subtypes,

    METHID_T = 0x21400,

    METHID_U = 0x21500,
    METHID_Update,
    METHID_UpdateFeature,

    METHID_V = 0x21600,

    METHID_W = 0x21700,
    METHID_Workspace,

    METHID_X = 0x21800,

    METHID_Y = 0x21900,

    METHID_Z = 0x21A00,

};

//
//
//

[
    uuid(DAE30B55-BB5F-436E-8A60-5E6CD71E9050),
    version(1.0),
    helpstring("ArcObjectsScript 1.0 Type Library")
]
library ArcObjectsScriptLib
{
    importlib("stdole2.tlb");

    //
    //
    //
    [
        object,
        uuid(2B86F8EE-B8D1-46DE-BF5F-D27FF81070C9),
        dual,
        nonextensible,
        helpstring("IArcObjects Interface"),
        pointer_default(unique)
    ]
    interface IArcObjects : IDispatch{
        [id(METHID_Domain)] HRESULT Domain([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Feature)] HRESULT Feature([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_FeatureClass)] HRESULT FeatureClass([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_FeatureDataset)] HRESULT FeatureDataset([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_FeatureLayer)] HRESULT FeatureLayer([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_FeatureLayerDefinition)] HRESULT FeatureLayerDefinition([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_FeatureLayerExtendedDefinition)] HRESULT FeatureLayerExtendedDefinition([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Field)] HRESULT Field([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Layer)] HRESULT Layer([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Map)] HRESULT Map([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_MapDocument)] HRESULT MapDocument([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_ObjectClass)] HRESULT ObjectClass([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_QueryFilter)] HRESULT QueryFilter([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Row)] HRESULT Row([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_SelectionSet)] HRESULT SelectionSet([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_SpatialReference)] HRESULT SpatialReference([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Subtypes)] HRESULT Subtypes([in, optional] VARIANT inner, [out, retval] VARIANT* outer);
        [id(METHID_Workspace)] HRESULT Workspace([in, optional] VARIANT inner, [out, retval] VARIANT* outer);

    };

    [
        uuid(28769970-F310-4461-8F7A-809170A485C9),
        helpstring("ArcObjects Class")
    ]
    coclass ArcObjects
    {
        [default] interface IArcObjects;
    };

    //
    //
    //

    [
        object,
        uuid(46D538AA-09F6-41b2-8B54-DCA59AD66335),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayer : IDispatch{
        [id(PROPID_FeatureClass), propget] HRESULT FeatureClass([out, retval] VARIANT* featureClass);
    }

    //
    //
    //

    [
        uuid(F486D1BA-6EB6-481F-B446-93908A1B55A0),
        helpstring("ArcObjectsFeatureLayer Class")
    ]
    coclass ArcObjectsFeatureLayer
    {
        [default] interface IArcObjectsFeatureLayer;
    };

    //
    //
    //

    [
        object,
        uuid(EDEBC24E-0607-4E49-89DD-44E65B5A4194),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayerDefinition Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayerDefinition : IDispatch{
        [id(PROPID_DefinitionExpression), propget] HRESULT DefinitionExpression([out, retval] BSTR* expression);
    };

    //
    //
    //

    [
        uuid(9841539F-1640-4957-A244-425BC461BA44),
        helpstring("ArcObjectsFeatureLayerDefinition Class")
    ]
    coclass ArcObjectsFeatureLayerDefinition
    {
        [default] interface IArcObjectsFeatureLayerDefinition;
    };

    //
    //
    //

    [
        object,
        uuid(1E2BF6C5-97DB-453A-97DC-2A67F5600652),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureLayerExtendedDefinition Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureLayerExtendedDefinition : IDispatch{
    };

    //
    //
    //

    [
        uuid(A4F5A94C-41B0-4C8B-B421-4497EE3C53D6),
        helpstring("ArcObjectsFeatureLayerExtendedDefinition Class")
    ]
    coclass ArcObjectsFeatureLayerExtendedDefinition
    {
        [default] interface IArcObjectsFeatureLayerExtendedDefinition;
    };

    //
    //
    //

    [
        object,
        uuid(6B8647B7-618D-4CCF-85D4-1DA37A5A850E),
        dual,
        nonextensible,
        helpstring("IArcObjectsMapDocument Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsMapDocument : IDispatch{
        [id(PROPID_MapCount), propget] HRESULT MapCount([out, retval] LONG* mapCount);
        [id(METHID_Map)] HRESULT Map(LONG index, [out, retval] VARIANT* map);
    };

    //
    //
    //

    [
        uuid(F4441B0B-52FA-4064-AFFF-EFA435D72773),
        helpstring("ArcObjectsMapDocument Class")
    ]
    coclass ArcObjectsMapDocument
    {
        [default] interface IArcObjectsMapDocument;
    };

    //
    //
    //

    [
        object,
        uuid(6F983B78-D22F-4366-8BDC-523EFFAABD1D),
        dual,
        nonextensible,
        helpstring("IArcObjectsMap Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsMap : IDispatch{
        [id(PROPID_LayerCount), propget] HRESULT LayerCount([out, retval] LONG* layerCount);
        [id(METHID_Layer)] HRESULT Layer(LONG index, [out, retval] VARIANT* layer);
    };

    //
    //
    //

    [
        uuid(CFE34595-9E4F-4805-88F5-BA47E4E7BABA),
        helpstring("ArcObjectsMap Class")
    ]
    coclass ArcObjectsMap
    {
        [default] interface IArcObjectsMap;
    };

    //
    //
    //

    [
        object,
        uuid(273A1ED0-9C14-4E3F-AAEB-3A9611517225),
        dual,
        nonextensible,
        helpstring("IArcObjectsLayer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsLayer : IDispatch{
        [id(PROPID_Name), propget] HRESULT Name([out, retval] BSTR* name);
        [id(PROPID_Name), propput] HRESULT Name([in] BSTR name);
		[id(PROPID_Valid), propget] HRESULT Valid([out, retval] VARIANT_BOOL* valid);
		[id(PROPID_AreaOfInterest), propget] HRESULT AreaOfInterest([out, retval] VARIANT* aoi);
		[id(PROPID_MinimumScale), propget] HRESULT MinimumScale([out, retval] double* minimumScale);
		[id(PROPID_MinimumScale), propput] HRESULT MinimumScale([in] double maximumScale);
		[id(PROPID_MaximumScale), propget] HRESULT MaximumScale([out, retval] double* maximumScale);
		[id(PROPID_MaximumScale), propput] HRESULT MaximumScale([in] double maximumScale);
		[id(PROPID_Visible), propget] HRESULT Visible([out, retval] VARIANT_BOOL* visible);
		[id(PROPID_Visible), propput] HRESULT Visible([in] VARIANT_BOOL visible);
		[id(PROPID_ShowTips), propget] HRESULT ShowTips([out, retval] VARIANT_BOOL* showTips);
		[id(METHID_GetTipText)] HRESULT GetTipText([in] double x, [in] double y, [in] double tolerance, [out, retval] BSTR* text);
		[id(PROPID_Cached), propget] HRESULT Cached([out, retval] VARIANT_BOOL* cached);
		[id(PROPID_Cached), propput] HRESULT Cached([in] VARIANT_BOOL cached);
		[id(PROPID_SupportedDrawPhases), propget] HRESULT SupportedDrawPhases([out, retval] LONG* drawPhases);
		[id(PROPID_SpatialReference), propput] HRESULT SpatialReference([in] VARIANT spatialReference);
		[id(METHID_Draw)] HRESULT Draw([in] LONG drawPhase, [in] VARIANT display, [in] VARIANT trackCancel);

	};

    //
    //
    //

    [
        uuid(E56DAD49-03A9-4AB3-8E9D-D861F98B95A3),
        helpstring("ArcObjectsLayer Class")
    ]
    coclass ArcObjectsLayer
    {
        [default] interface IArcObjectsLayer;
    };

    //
    //
    //

    [
        object,
        uuid(22B75AA7-23FC-4F76-8471-C20789509FF1),
        dual,
        nonextensible,
        helpstring("IArcObjectsSubtypes Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsSubtypes : IDispatch{
        [id(PROPID_HasSubtype), propget] HRESULT HasSubtype([out, retval] VARIANT_BOOL* hasSubtype);
        [id(PROPID_DefaultSubtypeCode), propget] HRESULT DefaultSubtypeCode([out, retval] LONG* subtypeCode);
        [id(PROPID_DefaultSubtypeCode), propput] HRESULT DefaultSubtypeCode([in] LONG subtypeCode);
        [id(METHID_GetDefaultValue)] HRESULT GetDefaultValue([in] LONG subtypeCode, [in] BSTR fieldName, [out, retval] VARIANT* value);
        [id(METHID_SetDefaultValue)] HRESULT SetDefaultValue([in] LONG subtypeCode, [in] BSTR fieldName, [in] VARIANT value);
        [id(METHID_GetDomain)] HRESULT GetDomain([in] LONG subtypeCode, [in] BSTR fieldName, [out, retval] VARIANT* domain);
        [id(METHID_SetDomain)] HRESULT SetDomain([in] LONG subtypeCode, [in] BSTR fieldName, [in] VARIANT domain);
        [id(PROPID_SubtypeFieldName), propget] HRESULT SubtypeFieldName([out, retval] BSTR* fieldName);
        [id(PROPID_SubtypeFieldName), propput] HRESULT SubtypeFieldName([in] BSTR fieldName);
        [id(PROPID_SubtypeFieldIndex), propget] HRESULT SubtypeFieldIndex([out, retval] LONG* index);
        [id(METHID_GetSubtypeName)] HRESULT GetSubtypeName([in] LONG subtypeCode, [out, retval] BSTR* value);
        [id(PROPID_Subtypes), propget] HRESULT Subtypes([out, retval] VARIANT* subtypes);
        [id(METHID_AddSubtype)] HRESULT AddSubtype([in] LONG subtypeCode, [in] BSTR subtypeName);
        [id(METHID_DeleteSubtype)] HRESULT DeleteSubtype([in] LONG subtypeCode);
    };

    //
    //
    //

    [
        uuid(9CED7FA7-2522-4730-805E-88555783F05C),
        helpstring("ArcObjectsSubtypes Class")
    ]
    coclass ArcObjectsSubtypes
    {
        [default] interface IArcObjectsSubtypes;
    };

    //
    //
    //

    [
        object,
        uuid(4BBBE44F-A3BA-40F0-ACA5-C5396C3D9FBD),
        dual,
        nonextensible,
        helpstring("IArcObjectsDomain Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsDomain : IDispatch{
        [id(PROPID_DomainID), propget] HRESULT DomainID([out, retval] LONG* domainID);
        [id(PROPID_DomainID), propput] HRESULT DomainID([in] LONG domainID);
        [id(PROPID_Description), propget] HRESULT Description([out, retval] BSTR* description);
        [id(PROPID_Description), propput] HRESULT Description([in] BSTR description);
        [id(PROPID_FieldType), propget] HRESULT FieldType([out, retval] LONG* fieldType);
        [id(PROPID_FieldType), propput] HRESULT FieldType([in] LONG fieldType);
        [id(PROPID_MergePolicy), propget] HRESULT MergePolicy([out, retval] LONG* mergePolicy);
        [id(PROPID_MergePolicy), propput] HRESULT MergePolicy([in] LONG mergePolicy);
        [id(PROPID_SplitPolicy), propget] HRESULT SplitPolicy([out, retval] LONG* splitPolicy);
        [id(PROPID_SplitPolicy), propput] HRESULT SplitPolicy([in] LONG splitPolicy);
        [id(PROPID_Name), propget] HRESULT Name([out, retval] BSTR* name);
        [id(PROPID_Name), propput] HRESULT Name([in] BSTR name);
        [id(PROPID_Owner), propget] HRESULT Owner([out, retval] BSTR* description);
        [id(PROPID_Owner), propput] HRESULT Owner([in] BSTR description);
        [id(PROPID_Type), propget] HRESULT Type([out, retval] LONG* type);
        [id(METHID_MemberOf)] HRESULT MemberOf([in] VARIANT value, [out, retval] VARIANT_BOOL* isMember);
    };

    //
    //
    //

    [
        uuid(3C7DB8B9-C332-4188-822C-9815CA65222A),
        helpstring("ArcObjectsDomain Class")
    ]
    coclass ArcObjectsDomain
    {
        [default] interface IArcObjectsDomain;
    };

    //
    //
    //

    [
        object,
        uuid(BD55CC31-347E-4E17-A00F-182A9D04BED3),
        dual,
        nonextensible,
        helpstring("IArcObjectsClass Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsClass : IDispatch{
        [id(METHID_FindField)] HRESULT FindField([in] BSTR name, [out, retval] LONG* fieldIndex);
        [id(PROPID_Fields), propget] HRESULT Fields([out, retval] VARIANT* fields);
        [id(PROPID_Indexes), propget] HRESULT Indexes([out, retval] VARIANT* indexes);
        [id(METHID_AddField)] HRESULT AddField([in] VARIANT field);
        [id(METHID_DeleteField)] HRESULT DeleteField([in] VARIANT field);
        [id(METHID_AddIndex)] HRESULT AddIndex([in] VARIANT index);
        [id(METHID_DeleteIndex)] HRESULT DeleteIndex([in] VARIANT index);
        [id(PROPID_HasOID), propget] HRESULT HasOID([out, retval] VARIANT_BOOL* hasOID);
        [id(PROPID_OIDFieldName), propget] HRESULT OIDFieldName([out, retval] BSTR* name);
        [id(PROPID_CLSID), propget] HRESULT CLSID([out, retval] VARIANT* clsid);
        [id(PROPID_EXTCLSID), propget] HRESULT EXTCLSID([out, retval] VARIANT* clsid);
        [id(PROPID_Extension), propget] HRESULT Extension([out, retval] VARIANT* extension);
        [id(PROPID_ExtensionProperties), propget] HRESULT ExtensionProperties([out, retval] VARIANT* extensionProperties);

    };

    //
    //
    //

    [
        uuid(1CBEC865-753B-47F3-952F-D87386824729),
        helpstring("ArcObjectsClass Class")
    ]
    coclass ArcObjectsClass
    {
        [default] interface IArcObjectsClass;
    };

    //
    //
    //

    [
        object,
        uuid(657B1AEC-BE5B-4DAC-8256-4014EE9E4360),
        dual,
        nonextensible,
        helpstring("IArcObjectsObjectClass Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsObjectClass : IArcObjectsClass{
        [id(PROPID_ObjectClassID), propget] HRESULT ObjectClassID([out, retval] LONG* objectClassID);
        [id(PROPID_RelationshipClasses), propget] HRESULT RelationshipClasses([in] LONG relRole, [out, retval] VARIANT* relationshipClasses);
        [id(PROPID_AliasName), propget] HRESULT AliasName([out, retval] BSTR* name);

    };

    //
    //
    //

    [
        uuid(B8EF8668-B6E8-4C73-92A3-46CA75F78EDB),
        helpstring("ArcObjectsObjectClass Class")
    ]
    coclass ArcObjectsObjectClass
    {
        [default] interface IArcObjectsObjectClass;
    };

    //
    //
    //

    [
        object,
        uuid(4BC4FDCF-878D-42DB-A28E-ED2927DC2D8E),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureClass Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureClass : IArcObjectsObjectClass {
        [id(PROPID_ShapeType), propget] HRESULT ShapeType([out, retval] LONG* geometryType);
        [id(PROPID_FeatureType), propget] HRESULT FeatureType([out, retval] LONG* featureType);
        [id(PROPID_ShapeFieldName), propget] HRESULT ShapeFieldName([out, retval] BSTR* fieldName);
        [id(PROPID_AreaField), propget] HRESULT AreaField([out, retval] VARIANT* field);
        [id(PROPID_LengthField), propget] HRESULT LengthField([out, retval] VARIANT* field);
        [id(PROPID_FeatureDataset), propget] HRESULT FeatureDataset([out, retval] VARIANT* featureDataset);
        [id(METHID_CreateFeature)] HRESULT CreateFeature([out, retval] VARIANT* feature);
        [id(METHID_GetFeatures)] HRESULT GetFeatures([in] VARIANT fids, [in] VARIANT_BOOL recycling, [out, retval] VARIANT* featureCursor);
        [id(METHID_CreateFeatureBuffer)] HRESULT CreateFeatureBuffer([out, retval] VARIANT* featureBuffer);
        [id(METHID_FeatureCount)] HRESULT FeatureCount([in] VARIANT queryFilter, [out, retval] LONG* numFeatures);
        [id(METHID_Search)] HRESULT Search([in] VARIANT queryFilter, [in] VARIANT_BOOL recycling, [out, retval] VARIANT* featureCursor);
        [id(METHID_Update)] HRESULT Update([in] VARIANT queryFilter, [in] VARIANT_BOOL recycling, [out, retval] VARIANT* featureCursor);
        [id(METHID_Insert)] HRESULT Insert([in] VARIANT_BOOL recycling, [out, retval] VARIANT* featureCursor);
        [id(METHID_Select)] HRESULT Select([in] VARIANT queryFilter, [in] LONG selectionType, [in] LONG selectionOption, [in] VARIANT workspace, [out, retval] VARIANT* selectionSet);

    };

    //
    //
    //

    [
        uuid(F031CF0C-88CA-482C-9FF8-188300272205),
        helpstring("ArcObjectsFeatureClass Class")
    ]
    coclass ArcObjectsFeatureClass
    {
        [default] interface IArcObjectsFeatureClass;
    };

    [
        object,
        uuid(56504920-EFE1-4448-9CD4-AD2C2DA28F31),
        dual,
        nonextensible,
        helpstring("IArcObjectsField Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsField : IDispatch{
        [id(PROPID_Name), propget] HRESULT Name([out, retval] BSTR* name);
    };

    //
    //
    //

    [
        uuid(46711B21-F34D-4EBB-BCB1-021909A1AA7C),
        helpstring("ArcObjectsField Class")
    ]
    coclass ArcObjectsField
    {
        [default] interface IArcObjectsField;
    };

    //
    //
    //

    [
        object,
        uuid(F4CB1C17-1F80-4FFF-99E8-BAA530B3C0A0),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureCursor Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureCursor : IDispatch{
        [id(METHID_FindField)] HRESULT FindField([in] BSTR name, [out, retval] LONG* fieldIndex);
        [id(PROPID_Fields), propget] HRESULT Fields([out, retval] VARIANT* fields);
        [id(METHID_NextFeature)] HRESULT NextFeature([out, retval] VARIANT* feature);
        [id(METHID_UpdateFeature)] HRESULT UpdateFeature([in] VARIANT feature);
        [id(METHID_DeleteFeature)] HRESULT DeleteFeature();
        [id(METHID_InsertFeature)] HRESULT InsertFeature([in] VARIANT featureBuffer, [out, retval] VARIANT* id);
        [id(METHID_Flush)] HRESULT Flush();
    };

    //
    //
    //

    [
        uuid(A959131E-E7B9-4441-846A-ADA93E68AFD2),
        helpstring("ArcObjectsFeatureCursor Class")
    ]
    coclass ArcObjectsFeatureCursor
    {
        [default] interface IArcObjectsFeatureCursor;
    };

    //
    //
    //

    [
        object,
        uuid(388BFECE-CC51-4A14-85F8-55F6C7EF1882),
        dual,
        nonextensible,
        helpstring("IArcObjectsQueryFilter Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsQueryFilter : IDispatch{
        [id(PROPID_SubFields), propget] HRESULT SubFields([out, retval] BSTR* subFields);
        [id(PROPID_SubFields), propput] HRESULT SubFields([in] BSTR subFields);
        [id(METHID_AddField)] HRESULT AddField([in] BSTR subField);
        [id(PROPID_WhereClause), propget] HRESULT WhereClause([out, retval] BSTR* subFields);
        [id(PROPID_WhereClause), propput] HRESULT WhereClause([in] BSTR subFields);
        [id(METHID_GetOutputSpatialReference)] HRESULT GetOutputSpatialReference([in] BSTR fieldName, [out, retval] VARIANT* spatialReference);
        [id(METHID_SetOutputSpatialReference)] HRESULT SetOutputSpatialReference([in] BSTR fieldName, [in] VARIANT spatialReference);
    };

    //
    //
    //

    [
        uuid(3B94564D-A3F3-4E56-B06C-530F90DC41FC),
        helpstring("ArcObjectsQueryFilter Class")
    ]
    coclass ArcObjectsQueryFilter
    {
        [default] interface IArcObjectsQueryFilter;
    };

    //
    //
    //

    [
        object,
        uuid(B218DED7-E3DC-48F0-8ACC-8721A2359B93),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeature Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeature : IDispatch{
    };

    //
    //
    //

    [
        uuid(AF008DFA-6F4F-4415-A9DF-0877C467F199),
        helpstring("ArcObjectsFeature Class")
    ]
    coclass ArcObjectsFeature
    {
        [default] interface IArcObjectsFeature;
    };

    //
    //
    //

    [
        object,
        uuid(A385267E-2B28-4532-9D59-0D75C3252CAA),
        dual,
        nonextensible,
        helpstring("IArcObjectsRow Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsRow : IDispatch{
    };

    //
    //
    //

    [
        uuid(C1D9ABB1-CDCB-422E-BBE2-F4474EDF3383),
        helpstring("ArcObjectsRow Class")
    ]
    coclass ArcObjectsRow
    {
        [default] interface IArcObjectsRow;
    };

    //
    //
    //

    [
        object,
        uuid(A6EDDC18-676E-4DA1-80B4-51E22AC20D6A),
        dual,
        nonextensible,
        helpstring("IArcObjectsSpatialReference Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsSpatialReference : IDispatch{
    };

    //
    //
    //

    [
        uuid(339C3A63-AEDF-442B-B5B3-A612F8FEA92D),
        helpstring("ArcObjectsSpatialReference Class")
    ]
    coclass ArcObjectsSpatialReference
    {
        [default] interface IArcObjectsSpatialReference;
    };

    //
    //
    //

    [
        object,
        uuid(045870E4-C01D-47DA-ABD7-5AE12BC4DEEB),
        dual,
        nonextensible,
        helpstring("IArcObjectsRowBuffer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsRowBuffer : IDispatch{
    };

    //
    //
    //

    [
        uuid(F31F451F-1745-45FD-BAA4-870702F1F8E9),
        helpstring("ArcObjectsRowBuffer Class")
    ]
    coclass ArcObjectsRowBuffer
    {
        [default] interface IArcObjectsRowBuffer;
    };

    //
    //
    //

    [
        object,
        uuid(9B1E4173-B553-4FDA-8206-B57BBBCA404A),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureBuffer Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureBuffer : IDispatch{
    };

    //
    //
    //

    [
        uuid(F657386C-3528-4509-B8DF-B7AA078F00C0),
        helpstring("ArcObjectsFeatureBuffer Class")
    ]
    coclass ArcObjectsFeatureBuffer
    {
        [default] interface IArcObjectsFeatureBuffer;
    };

    //
    //
    //

    [
        object,
        uuid(1C6949C5-EE65-46D4-BCC2-066D9AA4181A),
        dual,
        nonextensible,
        helpstring("IArcObjectsFeatureDataset Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsFeatureDataset : IDispatch{
    };

    //
    //
    //

    [
        uuid(6FAB68D7-92A3-4A9E-8C29-4B0C232F0A8E),
        helpstring("ArcObjectsFeatureDataset Class")
    ]
    coclass ArcObjectsFeatureDataset
    {
        [default] interface IArcObjectsFeatureDataset;
    };

    //
    //
    //

    [
        object,
        uuid(BC446B31-25E9-4E18-A628-05B4ECC2F592),
        dual,
        nonextensible,
        helpstring("IArcObjectsWorkspace Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsWorkspace : IDispatch{
    };

    //
    //
    //

    [
        uuid(8B7CEAC7-DDEC-47C9-ACD9-E16934E41D22),
        helpstring("ArcObjectsWorkspace Class")
    ]
    coclass ArcObjectsWorkspace
    {
        [default] interface IArcObjectsWorkspace;
    };

    //
    //
    //

    [
        object,
        uuid(556ECD7E-70E1-4975-A5D1-662DA1B68CFE),
        dual,
        nonextensible,
        helpstring("IArcObjectsSelectionSet Interface"),
        pointer_default(unique)
    ]
    interface IArcObjectsSelectionSet : IDispatch{
    };

    //
    //
    //

    [
        uuid(8ECEC491-F45D-4930-9300-DF16AD5D4E06),
        helpstring("ArcObjectsSelectionSet Class")
    ]
    coclass ArcObjectsSelectionSet
    {
        [default] interface IArcObjectsSelectionSet;
    };

	//
	//
	//

	[
		object,
		uuid(FEE504B6-4FE6-45CF-B1E3-786E17F01CD4),
		dual,
		nonextensible,
		helpstring("IArcObjectsEnvelope Interface"),
		pointer_default(unique)
	]
	interface IArcObjectsEnvelope : IDispatch {
	};

	//
	//
	//

	[
		uuid(B4F1F425-93FC-485E-8929-3A79C0669AF0),
		helpstring("ArcObjectsEnvelope Class")
	]
	coclass ArcObjectsEnvelope
	{
		[default] interface IArcObjectsEnvelope;
	};

	//
	//
	//

	[
		object,
		uuid(11A80BCB-403C-4A4B-B394-E78F4E446C86),
		dual,
		nonextensible,
		helpstring("IArcObjectsDisplay Interface"),
		pointer_default(unique)
	]
	interface IArcObjectsDisplay : IDispatch {
	};

	//
	//
	//

	[
		uuid(6E6A8B46-A4B4-4BE7-B5EB-2488CAD4855B),
		helpstring("ArcObjectsDisplay Class")
	]
	coclass ArcObjectsDisplay
	{
		[default] interface IArcObjectsDisplay;
	};

    //
    //
    //

	[
		object,
		uuid(D67EE815-88DE-4E53-B256-40538EB626AE),
		dual,
		nonextensible,
		helpstring("IArcObjectsTrackCancel Interface"),
		pointer_default(unique)
	]
	interface IArcObjectsTrackCancel : IDispatch {
	};

	//
	//
	//

	[
		uuid(7514AFCA-23CB-4D59-B66B-5D47DF6BF7F8),
		helpstring("ArcObjectsTrackCancel Class")
	]
	coclass ArcObjectsTrackCancel
	{
		[default] interface IArcObjectsTrackCancel;
	};

	//
	//
	//

};
