//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ArcObjectsScript.rc
//
#define IDS_PROJNAME 100
#define IDR_ARCOBJECTSSCRIPT 101
#define IDR_ARCOBJECTS 102
#define IDR_ARCOBJECTSFEATURELAYER 103
#define IDR_ARCOBJECTSFEATURELAYEREXTENDEDDEFINITION 104
#define IDR_ARCOBJECTSFEATURELAYERDEFINITION 105
#define IDR_ARCOBJECTSMAPDOCUMENT 106
#define IDR_ARCOBJECTSMAP 107
#define IDR_ARCOBJECTSLAYER 108
#define IDR_ARCOBJECTSFEATURECLASS 109
#define IDR_ARCOBJECTSSUBTYPES 110
#define IDR_ARCOBJECTSDOMAIN 111
#define IDR_ARCOBJECTSCLASS 112
#define IDR_ARCOBJECTSFIELD 113
#define IDR_ARCOBJECTSFEATURECURSOR 114
#define IDR_ARCOBJECTSQUERYFILTER 115
#define IDR_ARCOBJECTSFEATURE 116
#define IDR_ARCOBJECTSROW 117
#define IDR_ARCOBJECTSSPATIALREFERENCE 118
#define IDR_ARCOBJECTSROWBUFFER 119
#define IDR_ARCOBJECTSFEATUREBUFFER 120
#define IDR_ARCOBJECTSFEATUREDATASET 121
#define IDR_ARCOBJECTSWORKSPACE 122
#define IDR_ARCOBJECTSSELECTIONSET 123
#define IDR_ARCOBJECTSOBJECTCLASS 124
#define IDR_ARCOBJECTSENVELOPE 125
#define IDR_ARCOBJECTSDISPLAY 126
#define IDR_ARCOBJECTSTRACKCANCEL 127
#define IDR_ARCOBJECTSRELATIONSHIPCLASS 128
#define IDR_ARCOBJECTSOBJECT 129
#define IDR_ARCOBJECTSSET 130
#define IDR_ARCOBJECTSRULE 131
#define IDR_ARCOBJECTSRELATIONSHIP 132
#define IDR_ARCOBJECTSENUMRELATIONSHIPCLASS 133
#define IDR_ARCOBJECTSFIELDS 134
#define IDR_ARCOBJECTSSTANDALONETABLE 135
#define IDR_ARCOBJECTSSTANDALONETABLECOLLECTION 136
#define IDR_ARCOBJECTSTABLEFIELDS 137
#define IDR_ARCOBJECTSFIELDINFO 138
#define IDR_ARCOBJECTSTABLE 139
#define IDR_ARCOBJECTSNUMBERFORMAT 140


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 201
#define _APS_NEXT_COMMAND_VALUE 32768
#define _APS_NEXT_CONTROL_VALUE 201
#define _APS_NEXT_SYMED_VALUE 141
#endif
#endif
